### PR TITLE
dungeonsSeeder in Cairo

### LINKED ISSUE #1: Investigate: Reproduce random attribute generation on Starknet
Currently, attributes (e.g. size, environment, etc) are generated in `dungeonSeeder.sol` - https://github.com/threepwave/cryptsandcaverns/blob/main/contract/contracts/dungeonsSeeder.sol

When we move to Starknet, we have the option to send a packed message with these attributes. On the other hand, we could quickly generate them on Starknet.

We should investigate whether or not we can reliably reproduce the generation on Starknet if given a seed (e.g. send over the seed instead of each attribute).

Description of how things are packed: https://medium.com/@libertylocked/what-are-abi-encoding-functions-in-solidity-0-4-24-c1a90b5ddce8

ABI spec: https://docs.soliditylang.org/en/v0.8.0/abi-spec.html

This *MIGHT* be a reproduction of the source code: https://github.com/ethereumjs/ethereumjs-abi/blob/master/lib/index.js#L518

### PR DESCRIPTION
**Pull request by milancermak**
Resolves #1 

This PR adds an implementation of `random` from dungeonsSeeder.sol but in `Cairo`. It uses the `keccak256` implementation from the [starknet-l2-storage-verifier](https://github.com/OilerNetwork/starknet-l2-storage-verifier) (under GPL3). Since there's no library management in Starknet yet, I had to copy over the necessary files. There's also no established best practice on organizing a repo like this, so feel free to suggest changes to the structure. You'll probably need to set `CAIRO_PATH` envvar to point to the `contracts/starknet/lib` directory to get the file to compile.

I've tested the code using Python, just because I'm more used to it, but I'm happy to add a JS/TS tests, just want to align on where & how. Do you have some tests cases I should run?

There's probably some other quirks in the code or repo structure that don't make sense, but I've been staring at it for a while so I don't see it. Please point out anything that doesn't make sense.

### CODE REVIEW

**Comment by milancermak** [comment]
This last commit adds the remainder of `dungeonsSeeder.sol` in Cairo.

The `get_name` function returns a tuple `(legendary, affinity, output)` where `output` is a list of "felt encoded string literals". For example, `[358351644531, 32, 23490402093917555, 544171552, 140728386641114118617003891]` which translates to `["Sol's", " ", "Steppes", " of ", "the Willows"]`.

I use this python function to decode from felt to string:
```python
from itertools import zip_longest

# helper
def grouper(iterable, n, fillvalue=None):
    args = [iter(iterable)] * n
    return zip_longest(*args, fillvalue=fillvalue)

# translator function
def short_string_from_felt(felt : int) -> str:
    h = hex(felt)[2:] # drop '0x'
    chars = [chr(int(f"{c1}{c2}", 16)) for (c1, c2) in grouper(h, 2)]
    return ''.join(chars)
```

**Comment by threepwave** [comment]
> I've tested the code using Python, just because I'm more used to it, but I'm happy to add a JS/TS tests, just want to align on where & how. Do you have some tests cases I should run?

I have a metric ton of test cases for the solidity contract but haven't started writing tests for the Cairo code yet (was initially going to start prototyping and then decided to just run at a production version.

As we've been moving forward with this, I'm thinking we should split out the solidity and cairo code. It's really tough to navigate the directory structure, build scripts, etc. What would you think of a separate base folder:
`/contract-solidity/`
`contract-cairo/` or something like that ?

Within that structure, I suggest we have a `test` folder which contains one file per contract. That folder is primarily integration tests for the functions in said contract.

So for example we'd have `/contract-cairo/test/l1bridge.js`, `/contract-cairo/test/dungeons.js` etc.

I would prefer to write tests in js if possible (though I know the cairo is more python-centric). I'm not as familiar w/ python and am not confident I can do high quality code reviews in that language.

What do you think?

**Comment by threepwave** [comment]
> The `get_name` function returns a tuple `(legendary, affinity, output)` where `output` is a list of "felt encoded string literals". For example, `[358351644531, 32, 23490402093917555, 544171552, 140728386641114118617003891]` which translates to `["Sol's", " ", "Steppes", " of ", "the Willows"]`.

This looks great!! I assume other cairo contracts parse these strings from their string literals if needed? For example, if someone wanted to output the name on a svg that was generated in cairo, would that be possible? Or would they need a another language like python to do this translation?

**Comment by threepwave** [comment]
I think it would be helpful to add some additional comments explaining the `dungeonSeeder.cairo` contract. 

At least:
1. 1-2 line description of each function
2. describe each block, for example:
```
let (is_unique) = is_le(unique_seed, 16)
    if is_unique == 1:
        let (unique) = get_unique(unique_seed)

        let r : felt* = alloc()
        assert r[0] = unique
        return (1, 'none', 1, r)
    end
 ```
 3. Add a little bit of an explanation around how hash_uint256 works (I think I can follow but would be helpful to hear your thought process!!): 
 ```
 func hash_uint256{range_check_ptr, bitwise_ptr : BitwiseBuiltin*}(input : Uint256) -> (
 ```

Also might be worth considering breaking the reproduction of abi.encodePacked into a library that others could include/re-use?

**Comment by milancermak** [comment]
I'm fine with the proposed structure. Just so I don't mess it up, can you do that on `main` or even as a PR to this branch?

I'm also fine with having the test suite in JS. Will work on that next.

Out of curiosity, have you used foundry for Solidity testing?

**Comment by milancermak** [comment]
Added tests for `getName`, `getEnvironment` and `getSize` in the latest commit. They are marked as skipped because they take a long time, but I had all of them running locally and they all matched. In fact, the test suite found 4 errors in the Cairo implementation 🎉 

So I think we're good now. WDYT @threepwave?

**Comment by threepwave** [comment]
We're absolutely good! Just pulled this down and tested. Wrote some basic documentation that i'll push after I accept the pull request. This looks great!

**Pull request merged**
